name: CI/CD
on: 
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  # 开启手动部署
  workflow_dispatch:

jobs:
  build:
    name: Auto CI/CD
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: install pnpm
        run: npm i pnpm@latest -g
        
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
            
      - name: Build && Publish
        run: | 
          pnpm i
          pnpm -r build
          pnpm -r docker
      
      - name: Boot
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOYER }}
          password: ${{ secrets.DEPLOY_PWD }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: | 
            cd yuzhou/docker
            git checkout master
            git pull

            sh boot.sh