name: CI
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  # 开启手动部署
  workflow_dispatch:
jobs:
  build:
    name: Auto CI/CD
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Verify Change Logs
        run: node common/scripts/install-run-rush.js change --verify
      - name: Rush Install
        run: node common/scripts/install-run-rush.js install
      - name: Rush rebuild
        run: node common/scripts/install-run-rush.js rebuild --verbose --production
      
      # - name: Boot
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.DEPLOY_HOST }}
      #     username: ${{ secrets.DEPLOYER }}
      #     password: ${{ secrets.DEPLOY_PWD }}
      #     port: ${{ secrets.DEPLOY_PORT }}
      #     script: | 
      #       cd yingxv/docker
      #       git checkout master
      #       git pull

      #       sh boot.sh
